### ISSUE TITLE
[REQUEST] Donation - Thank You

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#1]
![sponsors-facebook](https://cloud.githubusercontent.com/assets/4682328/26784291/dcae9e1a-49ca-11e7-899e-7094ded2dd3b.png)
![sponsors-twitter](https://cloud.githubusercontent.com/assets/4682328/26784294/dd20abb8-49ca-11e7-873d-499384d9216f.png)

See with @yvesh for the text ;)

**Comment by brianteeman** [comment]
i guess this should be using the correct akeeba logo :)

**Comment by Sandra97** [comment]
If you have it, just send it to me and I'll change redo the pics

**Comment by brianteeman** [comment]
best to ask @nikosdion directly

**Comment by nikosdion** [comment]
<img width="363" alt="akeeba_4c 2x" src="https://user-images.githubusercontent.com/256041/26870430-9ff82a0e-4b78-11e7-97fe-d977f9773d72.png">
There you go and thank you very much! :)

**Comment by Sandra97** [comment]
Updated version
![facebook](https://user-images.githubusercontent.com/4682328/26889974-4fa80d90-4b86-11e7-8f3e-ef6843dbd5ce.png)
![twitter](https://user-images.githubusercontent.com/4682328/26889975-4fe6a000-4b86-11e7-8a64-48118cac1cb6.png)

@AlisonAMG @SigsiuTrinity @hvdmeer 
Could you please share them on our Social Media Channels?

**Comment by AlisonAMG** [comment]
Copy suggestion:
Thank you to @CloudAccess @RochenHost @akeebabackup @pixprostockholm for your dollar for dollar donation matching. #Joomla #community 

Are we using donations or another term? 

I noticed file names are changed here so you can't tell which image is which.

**Comment by SigsiuTrinity** [comment]
as we do not use donation but support, we need a different copy text

**Comment by SigsiuTrinity** [comment]
should the image also be changed?

**Comment by AlisonAMG** [comment]
Sandra - you have the art file for this image set. I can edit the photo to support from donation so we can still use the now familiar image.

**Comment by Sandra97** [comment]
GitHub doesn't support PSD file, I'll send you the PSD.
For the background image, if you need the original file, you can find it and download it in the download history of 123RF

**Comment by AlisonAMG** [comment]
I have the original and have edited it. Just have to put into the various formats and we are good to go.

**Comment by AlisonAMG** [comment]
![support-facebook-1200x630](https://user-images.githubusercontent.com/3825882/27041447-03024f98-4f62-11e7-94d0-b572a072be89.png)

Here is the FB image. Sandra do you have the Twitter and Instagram files for this layout and I'll drop the image in for them also.

**Comment by Sandra97** [comment]
For Twitter, use the Facebook one and resize it to 1024x512. That's what I'm doing all the time, to not waste my time ;)
For Instagram, just send me the background picture and I will do it

**Comment by AlisonAMG** [comment]
I tried that and it looked OK too. The picture is in the 123rf assets now as support. I left it in layers in case we want to change it again.

**Comment by AlisonAMG** [comment]
![support-twitter 1024x512](https://user-images.githubusercontent.com/3825882/27043329-c0a04c8a-4f67-11e7-8f38-7d07874b9e7a.png)

Please Git quit changing names.

**Comment by AlisonAMG** [comment]
Tw, LIn, G+, FBGroup all done

**Comment by SigsiuTrinity** [comment]
FB done

**Comment by yvesh** [comment]
So can we close this? :-)

**Comment by SigsiuTrinity** [comment]
I think so

**Comment by Sandra97** [comment]
Posted on Instagram
