### ISSUE TITLE
[REQUEST] cmscritic awards

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/socialmedia#12]
### Description: 
Could we promote this https://www.cmscritic.com/awards/ ?

**Comment by Sandra97** [comment]
I've asked for a blogpost yesterday and I did the pic. Parth has written it so we will just have to share it. Just give me time to read it and if all ok I'll publish it on cjo and tell you when redy to be shared

**Comment by Radek-Suski** [comment]
ah, sorry then

**Comment by Sandra97** [comment]
Here is the blogpost if you want to review and comment it:
https://docs.google.com/document/d/1xJGCl2JT0erT3QpS5CEhnk9IwrtMdKvcJSaE1Ax2JVk/edit#

**Comment by AlisonAMG** [comment]
Quick copy grab and image for reposting this quick later.

The CMS Critic Awards - Nominate Joomla! and let's make it happen again! #Joomla #cms #cmsawards
https://community.joomla.org/blogs/community/3120-the-cms-critic-awards-nominate-joomla-today.html

![joomla-cms-critic-2017](https://user-images.githubusercontent.com/3825882/27602794-02821724-5b42-11e7-9d88-e77c0a0b47b0.jpg)

**Comment by Sandra97** [comment]
As nominations run until August 27, this should be shared regularly on some of our SM accounts.
(FYI, over 700 nominations received so far)

**Comment by Sandra97** [comment]
Please re-share it during the upcoming week (10-14 July) on Twitter & Facebook.

**Comment by SigsiuTrinity** [comment]
shared 27 June ; re-shared 24 July

**Comment by SigsiuTrinity** [comment]
please re-share around 20th August

**Comment by Sandra97** [comment]
Re-shared one also on August 24th.
Closing this issue as votes end on 27th.
