### ISSUE TITLE
[JDAY] IMAGERY for JDay Kuala Lumpur Malaysia -12 August 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#13]
Facebook
![jday-malaysia-facebook](https://user-images.githubusercontent.com/4682328/27762053-7c7560d4-5e37-11e7-8fb8-0bc5bc26f1b2.png)

Instagram
![jday-malaysia-instagram](https://user-images.githubusercontent.com/4682328/27762054-7c9a6ab4-5e37-11e7-94f3-ac6bfc248588.png)

Twitter
![jday-malaysia-twitter](https://user-images.githubusercontent.com/4682328/27762055-7c9f464c-5e37-11e7-9b7a-7fcd900da8d5.png)

**Comment by AlisonAMG** [comment]
Join JoomlaDay Kuala Lumpur, Malaysia on August 12th #Joomla #jdkl17 
https://community.joomla.org/events/joomladays/3472-joomladay-kuala-lumpur-malaysia-2017.html

Posted this G+, FBG

**Comment by Sandra97** [comment]
Done on Instagram too.

**Comment by SigsiuTrinity** [comment]
The JoomlaDay Malaysia is postponed as the venue sponsor cancelled as they have internal events taking place. The team moved the event to December 2017.

**Comment by SigsiuTrinity** [comment]
do we post an 'event postboned' post?

**Comment by Sandra97** [comment]
As far as i know, no we don't have that. So I presume someone will need to create it

**Comment by SigsiuTrinity** [comment]
moved to internal repo
