### ISSUE TITLE
[REGULAR POST] Invite users to update their sites to the latest version

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#15]
If you look at  the [[stats]](https://developer.joomla.org/about/stats.html), you'll see that less that 14% of websites are running the latest version. 

Would be great to regularly invite our users to update to the latest version to benefit from new features and security fix. As well as inviting them if they need help to ask any question on the forum and check the [FAQ on JDocs](https://docs.joomla.org/Category:FAQ). 

July 6-10, 2017:
- [x] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter Dev / retweet on J! (Sandra)
- [x] Instagram (Sandra)
- [x] LinkedIn (Hans, Alison)
- [x] Pinterest (Sigrid)
- [x] Facebook group (Alison)

**Comment by hvdmeer** [comment]
Good idea!
But I would like to see the stats from the last month or the months.  

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sandra97** [comment]
Ask @mbabker to write a script for that.
(me running fast)

**Comment by mbabker** [comment]
392286 last modified in last 90 days
181557 are 3.7.2 (46% of records modified)
250090 are 3.7 (63% of records modified)

**Comment by Sandra97** [comment]
Facebook
![facebook-stats](https://user-images.githubusercontent.com/4682328/27786651-f6aae8dc-5faf-11e7-9565-df1e180002be.png)

Twitter
![twitter-stats](https://user-images.githubusercontent.com/4682328/27786652-f6abc3d8-5faf-11e7-99ac-fb6403ce796e.png)

**Comment by Sandra97** [comment]
Better post it a few days after 3.7.3

Please check when done:
- [ ] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter (Alison, Hans)
- [ ] Instagram (Sandra)
- [ ] LinkedIn (Hans, Alison)
- [ ] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

**Comment by AlisonAMG** [comment]
FBG & G+ done and I saw TW and LIn completed also so marked them done.

**Comment by SigsiuTrinity** [comment]
the copywriting was missing:
#Update your #Joomla website and benefit from all new features and #security fixes!
https://downloads.joomla.org

**Comment by hvdmeer** [comment]
Should we keep this one open because it's a regular post or just set a new one somewhere in the future?

**Comment by AlisonAMG** [comment]
The copywriting was missing from where? I just checked G+, Tw, & FBG and copy was all in place.

**Comment by Sandra97** [comment]
Yes please leave it open.

And yes the copywriting was missing (thanks Ali to have did it). 
I can't prepare all pictures and all copywritings.  Any help to prepare the copywriting and pics for the regular post docs would be appreciated if anyone has a bot of time. 
I've been asking for help about these regular posts for over 7 months now.

**Comment by Sandra97** [comment]
As 3.7.4 has been released yesterday, would be a good idea to share it again as of July 27

Please check when done:
- [ ] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter (Alison or Hans or Sandra)
- [ ] LinkedIn (Hans or Alison)
- [ ] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

**Comment by Sandra97** [comment]
Merged to Glip tasks.
