### ISSUE TITLE
[JORG] Contribute

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#18]
- **Twitter**
You want to give back to #Joomla but don't know how? See how you can #contribute and join us!
https://www.joomla.org/contribute-to-joomla.html
#community #volunteers 
![contribute-twitter](https://user-images.githubusercontent.com/4682328/27845395-08d9d970-60fd-11e7-9689-3928a0c9d8fa.png)

- **Facebook**
You want to give back to Joomla! but don't know how? Whatever are your skills, you can help improving your favourite CMS! See how you can contribute and join us! https://www.joomla.org/contribute-to-joomla.html 
![contribute-facebook](https://user-images.githubusercontent.com/4682328/27845393-08d6b1b4-60fd-11e7-9999-8258e110889b.png)

![contribute-instagram](https://user-images.githubusercontent.com/4682328/27845394-08d70cc2-60fd-11e7-829f-05630b9b4a54.png)

**Comment by AlisonAMG** [comment]
G+ & FBG done. Hans did Tw & LIn.

**Comment by SigsiuTrinity** [comment]
done on fan page

**Comment by AlisonAMG** [comment]
Awesome!

**Comment by Sandra97** [comment]
Instagram ok too.

**Comment by Sandra97** [comment]
Merged to Glip tasks.
