### ISSUE TITLE
[REQUEST] Joomla! 4: George Wilson Interview

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#2]
YouTube Video to share where possible:
https://www.youtube.com/watch?v=JxVagjKq16g

See @ufuk-avcu for the text
- [x] Facebook fan page
- [x] Pinterest
- [x] Google+
- [x] Twitter
- [ ] Instagram
- [x] LinkedIn
- [x] Facebook group

**Comment by AlisonAMG** [comment]
I watched this earlier today. Really good interview but a better sound setup for future interviews would be a good idea. Great idea!

**Comment by SigsiuTrinity** [comment]
> See @ufuk-avcu for the text

can someone copy the text to this issue. Cannot find it atm.

**Comment by AlisonAMG** [comment]
@ufuk-avcu do you have text for this so we can get this shared out? Please n thanks :)

**Comment by Sandra97** [comment]
Watch the #interview of  @GW1992, release Leader for #Joomla! 4 and get an overview of what we can expect from J4.
https://www.youtube.com/watch?v=JxVagjKq16g

**Comment by Sandra97** [comment]
Closing this issue.
Can't share videos like these on Instagram
