### ISSUE TITLE
[DOWNLOADS] All versions

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#20]
All the downloads of every single #version are gathered on our #download #hub for your convenience. But always use our latest version to build a new #website! https://downloads.joomla.org/cms #cms #joomla 

Check when done:
- [x] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter (Alison)
- [ ] Instagram (Sandra)
- [ ] LinkedIn (Alison)
- [x] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

Facebook
![releases-facebook](https://user-images.githubusercontent.com/4682328/27845527-1bc38e72-60fe-11e7-9a92-1e4f3e1668f1.png)

Instagram
![releases-instagram](https://user-images.githubusercontent.com/4682328/27845528-1c338c36-60fe-11e7-86dd-b8d0dd960b1d.png)

Twitter
![releases-twitter](https://user-images.githubusercontent.com/4682328/27845529-1c36acd6-60fe-11e7-8ff5-29a6206e1f73.png)

**Comment by SigsiuTrinity** [comment]
done 17 July

**Comment by Sandra97** [comment]
Merged in Glip tasks.
