### ISSUE TITLE
[DOWNLOADS] Technical Requirements

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#21]
Wondering what #server setup you need, to run Joomla! #CMS? Find the #technical #requirements here: https://downloads.joomla.org/technical-requirements #hosting #internet

Facebook
![technical-requirements-facebook](https://user-images.githubusercontent.com/4682328/27845697-73680c88-60ff-11e7-9673-ab49f49c8364.png)

Instagram
![technical-requirements-instagram](https://user-images.githubusercontent.com/4682328/27845698-73c2a184-60ff-11e7-8adb-52348e8537ad.png)

Twitter
![technical-requirements-twitter](https://user-images.githubusercontent.com/4682328/27845699-73c3404e-60ff-11e7-81ee-a68307590fd8.png)

**Comment by AlisonAMG** [comment]
G+, FBG done by me and Hans has done Tw & LIn today.

**Comment by SigsiuTrinity** [comment]
done 20 July

**Comment by Sandra97** [comment]
Merged to Glip tasks.
