### ISSUE TITLE
[ISSUETRACKER]  Testers

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#23]
- **Facebook**
Love to squash or fix #bugs, test new features or write new awesome code? We would love you to #contribute to the Joomla! development! 
https://issues.joomla.org 
![issuetracker-facebook](https://user-images.githubusercontent.com/4682328/27890026-58ad53b6-61be-11e7-9740-0d98ad0707e1.png)

- **Twitter**
Love to squash or fix #bugs, test new features or write #code? #Contribute to the #joomla #development!
Join https://issues.joomla.org
#cms
![issuetracker-twitter](https://user-images.githubusercontent.com/4682328/27890028-58df3d0e-61be-11e7-89ed-301d206071bb.png)

- **Instagram**
![issuetracker-instagram](https://user-images.githubusercontent.com/4682328/27890027-58b463fe-61be-11e7-86ec-0f90f73f6efc.png)

**Comment by AlisonAMG** [comment]
G+, FBG for me and Hans did Tw & LIn

**Comment by Sandra97** [comment]
Done on July 19th:
- [x] Google+ (Alison)
- [x] Twitter (Hans)
- [x] Twitter Dev (Sandra)
- [x] Instagram (Sandra)
- [x] LinkedIn (Hans)
- [x] Facebook Group (Alison)

**Comment by SigsiuTrinity** [comment]
Facebook fan page
Pinterest

**Comment by Sandra97** [comment]
Merged to Glip tasks.
