### ISSUE TITLE
[REQUEST] JCM July 2017 issue now live

### ISSUE THREAD

**Issue by JacquesR** [joomla/socialmedia#24]
### Description: 
JCM July issue now live

### Date tweet should be done (at least 7 days upfront)

asap please.

### Twitter text (optional)
The July 2017 Issue of the Joomla Community Magazine is now live. 
#joomla #jcm #community #opensource #php #CMS 
https://magazine.joomla.org

### Facebook text (optional)
as above

**Comment by Sandra97** [comment]
Twitter ok - July 8th

**Comment by Sandra97** [comment]
We're July 30th, I'm closing this issue.
