### ISSUE TITLE
SysAdmin Day - Friday, July 28

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#26]
**TO POST ON 28 JULY** 

We may have a blogpost (or not). I will let you now

- [ ] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter (Sandra)
- [x] Instagram (Sandra)
- [x] LinkedIn (Hans, Alison)
- [ ] Pinterest (Sigrid)
- [x] Facebook Group (Alison)

- **Facebook**
![sysadmins-facebook](https://user-images.githubusercontent.com/4682328/28643263-41a1c9fc-7223-11e7-8fe5-293425a75c18.png)

- **Twitter**
![sysadmins-twitter](https://user-images.githubusercontent.com/4682328/28643276-5424b9ae-7223-11e7-85d6-47c341e12f7b.png)

- **Instagram**
![sysadmins-instagram](https://user-images.githubusercontent.com/4682328/28643284-5b8b02ca-7223-11e7-85f2-d06e66184979.png)

**Comment by Sandra97** [comment]
I'm closing this issue.
Obvioulsy, it has been posted everywhere except on the channels managed by Sigrid. :(
Pity as this task has been opened 19 days ago and could have been scheduled...

**Comment by SigsiuTrinity** [comment]
Wanted to share it on Friday but then Radek said to me that he told you to share something else instead. So I thought this was done.

**Comment by Sandra97** [comment]
yes Radek asked to share something else but no need to discuss of it here. 
Anyway, we can share several posts on the same day and even easier with the fanpage as it can be scheduled.
