### ISSUE TITLE
[DEV] JSST

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#27]
- **Twitter**
Joomla! takes #security #vulnerabilities very seriously. Learn more about the Security Strike Team
https://developer.joomla.org/security.html
#cms #websecurity
![jsst-twitter](https://user-images.githubusercontent.com/4682328/27995249-eb7f2a34-6498-11e7-8dd6-a8597666007f.png)

- **Facebook**
A secure code is fundamental for Joomla! and we take security vulnerabilities very seriously. Learn more about the Joomla! Security Strike Team on https://developer.joomla.org/security.html
![jsst-facebook](https://user-images.githubusercontent.com/4682328/27995247-eb145b78-6498-11e7-934e-066733e9c899.png)

- **Instagram**
![jsst-instagram](https://user-images.githubusercontent.com/4682328/27995248-eb171bd8-6498-11e7-9f25-bf0b48084e43.png)

**Comment by zero-24** [comment]
Sounds good to me Thanks :+1:

**Comment by Sandra97** [comment]
It's time to say thank you to the JSST for their hard work at fixing security vulnerabilities and keeping J! secure

Please check when done:
- [ ] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter (Alison or Hans or Sandra)
- [ ] LinkedIn (Hans or Alison)
- [ ] Pinterest (Sigrid)
- [ ] Facebook group (Alison)
- [ ] Instagram (Sandra)

**Comment by Sandra97** [comment]
Merged to Glip tasks.
