### ISSUE TITLE
[JDocs] Recover your password

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#29]
Can't log in your #Joomla backend? #JDocs has the fix!
Read the #tutorial How to recover your backend #password
http://bit.ly/2u1BBBd
#cms

- **Facebook**
![jdocs-password-facebook](https://user-images.githubusercontent.com/4682328/28040988-b2669e00-6595-11e7-8375-1a3ade7f8353.png)

- **Instagram**
![jdocs-password-instagram](https://user-images.githubusercontent.com/4682328/28040989-b2698066-6595-11e7-93dc-b45fdc2406b5.png)

- **Twitter**
![jdocs-password-twittter](https://user-images.githubusercontent.com/4682328/28040993-b2d2055a-6595-11e7-9005-c057b95db6ce.png)

**Comment by SigsiuTrinity** [comment]
posted on 3 August on FB and Pinterest

**Comment by Sandra97** [comment]
Merged to Glip tasks.
