### ISSUE TITLE
Joomladay Tanzania-Arusha

### ISSUE THREAD

**Issue by SigsiuTrinity** [joomla/socialmedia#3]
### Description: 
Please describe what and why you want something shared.

### Date tweet should be done (at least 7 days upfront)
https://community.joomla.org/events/joomladays/3536-joomladay-tanzania-arusha.html
Event Date: 01 July 2017
4 weeks upfront

### Facebook text (optional)
Upcoming Joomla! event: JoomlaDay Tanzania-Arusha
JoomlaDay Arusha, Tanzania is a one day event that focusses on Joomla! and sharing of stories that make Joomla! the platform preferred by millions of people around the world.

**Comment by Sandra97** [comment]
I will do the pics today

**Comment by Sandra97** [comment]
![jd-tanzania](https://user-images.githubusercontent.com/4682328/26944073-0652cf94-4c5e-11e7-84fe-fbbadf16f0bf.png)
![twitter-tanzania](https://user-images.githubusercontent.com/4682328/26944074-0670ea9c-4c5e-11e7-8ef3-d5f642234c76.png)

**Comment by AlisonAMG** [comment]
Tw, G+, LIn, FBgroup done

How do you mark a task complete for yourself?

**Comment by Sandra97** [comment]
- [ ] Alison
- [ ] Sigrid
- [ ] Hans
- [ ] Sandra

**Comment by Radek-Suski** [comment]
I would wait until tomorrow. Sunday isn't good day for sharing IMHO

**Comment by AlisonAMG** [comment]
LOL I think I hogged the many. We haven't had a Twitter post for several days so I got this one up there.

**Comment by Radek-Suski** [comment]
It looks like @SigsiuTrinity already posted it https://www.facebook.com/joomla/posts/10155071641184667

**Comment by AlisonAMG** [comment]
Funny that thought. The FBgroup post had many people hitting likes on it in minutes after it was posted.

**Comment by SigsiuTrinity** [comment]
I assigned it and posted it already on Friday.
Agree with @Radek-Suski , no postings on weekends, especially not on FB fan page.

**Comment by AlisonAMG** [comment]
I didn't touch the fan page

**Comment by AlisonAMG** [comment]
You had this one completed on Friday Sigrid. OK to close this now? :)

**Comment by SigsiuTrinity** [comment]
no, it has to be repeated every week on Twitter and one week before the event on the FB fan page. Therefore I haven't marked it as completed yet.
