### ISSUE TITLE
[REQUEST] JoomlaDay Italy - Call for sponsors

### ISSUE THREAD

**Issue by AlexRed** [joomla/socialmedia#30]
### Description: 
Please help me to shared info about JoomlaDay Italy.
Some important info:
- JoomlaDay Italy 
- City: Milan
- Date: 14 October 2017
- Location: Hotel Melià
- Site: www.joomladay.it
- Inscriptions are available, free entry for 1000 people
- Tenth edition
- Call for paper and call for sponsor are open.

### Additional comments
Sorry for my bad english

Please check when done (Call for Sponsors) :
- [x] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter (Hans, Alison, Sandra) July, 29th
- [ ] Instagram (Sandra)
- [x] LinkedIn (Hans, Alison)
- [x] Pinterest (Sigrid)
- [x] Facebook group (Alison)

**Comment by Sandra97** [comment]
@AlexRed Do you have any graphics we can use? Thanks!

**Comment by AlexRed** [comment]
Hello @Sandra97, thanks for your reply.
If you want you can use the badge, you can see it in the page: https://www.joomladay.it/l-evento
https://www.joomladay.it/images/banners/jd-badge2017-01.png

and also the location photos 
No other graphics materials...

**Comment by Sandra97** [comment]
Location pics and badge are enough so that I can create the pictures. Thank you!

**Comment by Sandra97** [comment]
- **Facebook**
![jday-facebook](https://user-images.githubusercontent.com/4682328/28093326-ce924442-6664-11e7-90a8-83c56c55190a.png)

- **Instagram**
![jday-instagram](https://user-images.githubusercontent.com/4682328/28093327-ce945fe8-6664-11e7-8750-490cdca02fe5.png)

- **Twitter**
![jday-twitter](https://user-images.githubusercontent.com/4682328/28093329-cefe8756-6664-11e7-9fe4-05ac6f1dbb07.png)

**Comment by AlexRed** [comment]
Fantastic.

Can also you write the text with the important info and share on the Joomla.org social account ?

Thanks for your help

**Comment by Sandra97** [comment]
For Twitter:
The 10th edition of #JoomlaDay #Italy will occur in #Milan on Oct. 14.
Free entry for 1,000 people! Register at joomladay.it
#joomla #event

For Facebook, we are not limited in character so we can also mention the call for sponsors/speakers.

Also, do you have a Twitter account and a hashtag?

**Comment by AlexRed** [comment]
ok, thanks.

hashtag: jdit17
twitter account: https://twitter.com/JoomlaItalia

**Comment by hvdmeer** [comment]
Shouldn't be hashtag from joomla's perspective be #jd17it ? Here in the Netherlands we used #jd17nl as official hashtag.

**Comment by Sandra97** [comment]
Agree with Hans. 
When we are sure, I'll redo the pics to add the hashtag on it

**Comment by AlexRed** [comment]
ok for #jd17it  :+1: 

I copy jdit17 form: https://github.com/joomla/socialmedia/issues/13

**Comment by Sandra97** [comment]
New version of the Tweet to mention the hahstag and Twitter account:

#JoomlaDay #Italy will occur in #Milan on Oct. 14
Free entry for 1,000 people! Register at joomladay.it
#joomla #jd17it @JoomlaItalia

**Comment by AlexRed** [comment]
no more 10th edition  :(

can you try with no twitter account?

10th edition of #JoomlaDay #Italy will occur in #Milan on Oct. 14
 Free entry for 1,000 people! Register at joomladay.it
 #joomla #jd17it

**Comment by Sandra97** [comment]
I can add 10th edition on the pic.

For Facebook and Instagram, we will do longer post with all information

I can also do a pic for your call for sponsors.
@AlexRed Could you provide a short text for it?

**Comment by Sandra97** [comment]
- **Facebook** 
![jday-facebook](https://user-images.githubusercontent.com/4682328/28111954-430db242-66c5-11e7-9d5c-08772e4f8fbc.png)

- **Instagram**
![jday-instagram](https://user-images.githubusercontent.com/4682328/28111955-430e922a-66c5-11e7-8fcc-e32a6eab4949.png)

- **Twitter**
![jday-twitter](https://user-images.githubusercontent.com/4682328/28111956-431655b4-66c5-11e7-8046-edbfe8b2a17f.png)

**Comment by AlexRed** [comment]
Thanks

The url for the call for sponsor form: https://www.joomladay.it/sponsor#proponiti
Many types of sponsorship plans. 1000 people from the italian Joomla community. Do not miss this opportunity for your business.

**Comment by Sandra97** [comment]
@AlexRed Here is the pics for the Call for Sponsors

- **Facebook**
![jday-italy-sponsor-facebook](https://user-images.githubusercontent.com/4682328/28142902-f8df91a6-6730-11e7-9cd2-7d45a8f004c5.png)

- **Instagram**
![jday-italy-sponsor-instagram](https://user-images.githubusercontent.com/4682328/28142903-f8e249dc-6730-11e7-9c3f-34dbf507214d.png)

- **Twitter**
![jday-italy-sponsor-twitter](https://user-images.githubusercontent.com/4682328/28142904-f951cc4e-6730-11e7-9e5f-e804dde27ba2.png)

**Comment by AlexRed** [comment]
ok, thanks  :+1:

**Comment by SigsiuTrinity** [comment]
text for FB:
The 10th edition of #JoomlaDay #Italy will occur in Milan on Oct. 14.
Call for papers are open.
Free entry for 1,000 people! Register now at joomladay.it
#joomla #jd17it  @joomlaitalia

**Comment by AlexRed** [comment]
ok, Thanks

**Comment by SigsiuTrinity** [comment]
JoomlaDay done 19 July

**Comment by Sandra97** [comment]
Tasks moved to Glip.
Closing this issue.
