### ISSUE TITLE
[JDAY] JoomlaDay Israel - 12 September 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#32]
- **Facebook**
![jd-israel-facebook](https://user-images.githubusercontent.com/4682328/28247112-3bb156e4-69f8-11e7-81bc-cf7a6600415d.png)

- **Instagram**
![jd-israel-instagram](https://user-images.githubusercontent.com/4682328/28247113-3bd48060-69f8-11e7-9ed5-039f7187c7f9.png)

- **Twitter**
![jd-israel-twitter](https://user-images.githubusercontent.com/4682328/28247114-3bd74d5e-69f8-11e7-9524-470bfc2cde0d.png)

**Comment by SigsiuTrinity** [comment]
moved to internal repo
