### ISSUE TITLE
[JDAY] JoomlaDay Germany - 22-23 September 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#33]
- **Facebook**
![jd-germany-facebook](https://user-images.githubusercontent.com/4682328/28247286-6def9816-69fb-11e7-8094-05b2544c59ee.png)

- **Instagram**
![jd-germany-instagram](https://user-images.githubusercontent.com/4682328/28247287-6e109fd4-69fb-11e7-9943-75691cc271bf.png)

- **Twitter**
![jd-germany-twitter](https://user-images.githubusercontent.com/4682328/28247288-6e13be26-69fb-11e7-9324-c4d122792968.png)

**Comment by SigsiuTrinity** [comment]
moved to internal repo
