### ISSUE TITLE
[JDAY] JoomlaDay Poland - 23-24 September 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#34]
- **Facebook**
![jd-poland-facebook](https://user-images.githubusercontent.com/4682328/28247447-a334ad6a-69fe-11e7-8848-acb00a9f79f6.png)

- **Instagram**
![jd-poland-instagram](https://user-images.githubusercontent.com/4682328/28247448-a33962b0-69fe-11e7-9645-6998537fe026.png)

- **Twitter**
![jd-poland-twitter](https://user-images.githubusercontent.com/4682328/28247449-a42ec37c-69fe-11e7-9fcc-5370338fc928.png)

**Comment by SigsiuTrinity** [comment]
moved to internal repo
