### ISSUE TITLE
[JDAY] Joomladay Chicago - 23 September 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#35]
- **Facebook**
![jd-chicago-facebook](https://user-images.githubusercontent.com/4682328/28247610-f15fa492-6a01-11e7-8ff1-c2f03925a798.png)

- **Instagram**
![jd-chicago-instagram](https://user-images.githubusercontent.com/4682328/28247611-f1c66e66-6a01-11e7-995a-bb8be5933389.png)

- **Twitter**
![jd-chicago-twitter](https://user-images.githubusercontent.com/4682328/28247612-f1ce8ccc-6a01-11e7-88ed-978c29d29f51.png)

**Comment by SigsiuTrinity** [comment]
moved to internal repo
