### ISSUE TITLE
OpenSource Friday  - 21 July 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#37]
For this coming Friday, what about doing a post asking people to submit their ideas of posts on our GitHub repo in order to see what they would like our team to talk about? 

- **Facebook**
![opensource-facebook](https://user-images.githubusercontent.com/4682328/28395288-e433d5d8-6cc0-11e7-88b9-d863174b382c.png)

- **Instagram**
![opensource-instagram](https://user-images.githubusercontent.com/4682328/28395290-e56df6c2-6cc0-11e7-8832-f95cd3dc15ff.png)

- **Twitter*
![opensource-twitter](https://user-images.githubusercontent.com/4682328/28395289-e48ef8f0-6cc0-11e7-938d-5664b3ce6113.png)

**Comment by AlisonAMG** [comment]
Hans has done TW & LIn and I have done G+ & FBG

**Comment by Sandra97** [comment]
I did Instagram too.
We should be good for this one.
I'm closing this issue.
