### ISSUE TITLE
[VOLUNTEERS] Banners

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#38]
Check when done:
- [x] Facebook fan page (Sigrid)
- [ ] Google+ (Alison)
- [ ] Twitter (Alison)
- [ ] Instagram (Sandra)
- [ ] LinkedIn (Alison)
- [x] Pinterest (Sigrid)
- [ ] Facebook group (Alison)

- **Twitter**
Spread your #love for #Joomla! Use the banners on your #website to show you are a proud #Joomler & supporting Joomla
https://volunteers.joomla.org/banners
![vp-banners-twitter](https://user-images.githubusercontent.com/4682328/28440977-8e3d27e0-6d76-11e7-9c11-d2404af04233.png)

- **Instagram**
![vp-banners-instagram](https://user-images.githubusercontent.com/4682328/28440978-8e4298e2-6d76-11e7-9ac9-f6bf57e0a14d.png)

- **Facebook**
![vp-banners-facebook](https://user-images.githubusercontent.com/4682328/28440979-8e4e90fc-6d76-11e7-8518-690ca0e57ee1.png)

**Comment by SigsiuTrinity** [comment]
done 28 July

**Comment by Sandra97** [comment]
Merged to Glip tasks.
