### ISSUE TITLE
[Trademark Team] Promoting the call for volunteers / manifesto of the Trademark Team

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/socialmedia#39]
https://volunteers.joomla.org/teams/trademark-team/reports/603-help-us-building-a-new-trademark-team

Please check when done
- [x] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter (Alison)
- [x] Instagram (Sandra)
- [x] LinkedIn (Alison)
- [x] Pinterest (Sigrid)
- [x] Facebook group (Alison)

**Comment by Sandra97** [comment]
- **Twitter**
![vp-twitter](https://user-images.githubusercontent.com/4682328/28499934-942aef88-6f8e-11e7-973d-c901c885521d.png)

- **Facebook**
![vp-facebook](https://user-images.githubusercontent.com/4682328/28499948-b284a76c-6f8e-11e7-84b8-2ea0e3afb024.png)

- **Instagram**
![vp-instagram](https://user-images.githubusercontent.com/4682328/28499957-d9341c58-6f8e-11e7-8307-cc9bb4ba33fd.png)

**Comment by jeckodevelopment** [comment]
Thank you :)

**Comment by AlisonAMG** [comment]
Done on G+, FBG, TW, LIn 7/24

**Comment by Sandra97** [comment]
Done on Instagram  - July, 26

**Comment by jeckodevelopment** [comment]
THANK YOU :)

**Comment by Sandra97** [comment]
Shared everywhere, we can close this issue.
