### ISSUE TITLE
Joomladay UK

### ISSUE THREAD

**Issue by SigsiuTrinity** [joomla/socialmedia#4]
### Description: 
Please describe what and why you want something shared.
https://community.joomla.org/events/joomladays/3535-joomladay-uk-2017.html
Event Date: 08 July 2017

### Date tweet should be done (at least 7 days upfront)
4 weeks upfront

### Facebook text (optional)
Upcoming Joomla! event: JoomlaDay UK 2017
JoomlaDay UK will be held on the 8th of July 2017 at the Ilec Conference Centre in West Brompton, London.

- [x] Facebook fan page
- [x] Google+
- [x] Twitter
- [ ] Instagram
- [x] LinkedIn
- [x] Pinterest
- [x] Facebook group

**Comment by Sandra97** [comment]
Rowan will send me a graphic so that I can create the pictures.

**Comment by Sandra97** [comment]
Facebook
![jdayuk-facebook](https://user-images.githubusercontent.com/4682328/27084577-c875d324-5022-11e7-9d98-5f046d2da89e.png)

Twitter
![jdayuk-twitter](https://user-images.githubusercontent.com/4682328/27084578-c8b3fa64-5022-11e7-9432-660916b045e3.png)

**Comment by SigsiuTrinity** [comment]
added images to the repository

**Comment by Sandra97** [comment]
And finally, the Instagram version
![jduk-instagram](https://user-images.githubusercontent.com/4682328/27098679-da20884a-504e-11e7-9bdf-1bd397dbceeb.png)

**Comment by SigsiuTrinity** [comment]
image added to the repository

**Comment by SigsiuTrinity** [comment]
- [ ] Facebook fan page
- [ ] Google+
- [ ] Twitter
- [ ] Instagram
- [ ] LinkedIn
- [ ] Pinterest
- [ ] Facebook group

**Comment by AlisonAMG** [comment]
They turned out great Sandra!

**Comment by AlisonAMG** [comment]
Not sure the need to store images in a repository since we can access them from social accounts if needed.

**Comment by AlisonAMG** [comment]
Get your tickets now for #JDayUK July 8th. We have a great speaker line up. Don't miss out! #joomla #event #cms http://www.joomla-day.uk/
