### ISSUE TITLE
RFP - Google Domains

### ISSUE THREAD

**Issue by Joomv** [joomla/socialmedia#41]
Please could you push the following out on social.
Thanks
https://www.opensourcematters.org/organisation/requests-for-proposals/259-request-for-proposal-google-domains-integration.html

Check when done:
- [x] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter (Alison)
- [x] Instagram (Sandra)
- [x] LinkedIn (Alison)
- [x] Pinterest (Sigrid)
- [x] Facebook group (Alison)

**Comment by Sandra97** [comment]
I'll first create a pic of it to get better visibility

**Comment by Sandra97** [comment]
- **Facebook**
![rfp-facebook](https://user-images.githubusercontent.com/4682328/28575832-78d5ea4e-7128-11e7-937e-d2b96f5736de.png)

- **Twitter**
![rfp-twitter](https://user-images.githubusercontent.com/4682328/28575833-79578450-7128-11e7-885b-6ed81a253bb4.png)

I will prepare Instagram when I can

**Comment by Sandra97** [comment]
- **Instagram**
![rfp-instagram](https://user-images.githubusercontent.com/4682328/28576611-b465ed28-712a-11e7-85ff-71dfb54e1352.png)

**Comment by AlisonAMG** [comment]
Tw, LIn, G+, FBG posted

**Comment by Joomv** [comment]
You guys rock! Thank you!

**Comment by AlisonAMG** [comment]
Glad to help :)

**Comment by Sandra97** [comment]
Check when done:
- [ ] Facebook fan page (Sigrid)
- [x] Google+ (Alison)
- [x] Twitter (Alison)
- [ ] Instagram (Sandra)
- [x] LinkedIn (Alison)
- [ ] Pinterest (Sigrid)
- [x] Facebook group (Alison)

**Comment by Sandra97** [comment]
Will today on Instagram tomorrow. Today, it's release post!

**Comment by Sandra97** [comment]
It seems it hasn't been posted on the FanPage and deadline for questions is August 1st

**Comment by Radek-Suski** [comment]
oops

**Comment by Sandra97** [comment]
Closing this issue as it has been shared everywhere.
