### ISSUE TITLE
[DEV] Nightly Builds

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#44]
I've just realised that most users have no idea they can download and test upcoming versions from the Dev site.

It could be a nice idea to inform them about that and invite them to visit (and read) https://developer.joomla.org/nightly-builds.html where they can download and test J3.8, 3.9, 4.0. 

We can start by J4  as it can reach more people.
I'll provide the text later. 

_(Images updated on August, 28)_
- **Facebook**
![facebook](https://user-images.githubusercontent.com/4682328/29794409-dae1a248-8c15-11e7-9515-0f7ca9762a6a.png)

- **Instagram**
![instagram](https://user-images.githubusercontent.com/4682328/29794424-eb083330-8c15-11e7-8e25-88f10a55bc2a.png)

- **Twitter**
![twitter](https://user-images.githubusercontent.com/4682328/29794467-0ca7df7c-8c16-11e7-94b8-095ea94ec331.png)

**Comment by AlisonAMG** [comment]
Very cool thanks always Sandra!

**Comment by C-Lodder** [comment]
Just FYI, the screenshots for the Joomla 4 dashboard are a little outdated :)

**Comment by Sandra97** [comment]
I'll redo it ;)

**Comment by Sandra97** [comment]
Merged to Glip tasks.
