### ISSUE TITLE
[JORG] joomla.org newsletter

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#5]
Joomla.org Newsletter to promote regularly to get new subscribers.
https://www.joomla.org/newsletter.html

Due date: June 14th, 2017

![joomla-newsletter](https://user-images.githubusercontent.com/4682328/27985851-d5469d06-63c1-11e7-9cec-645df60b0913.jpg)

![newsletterjorg](https://user-images.githubusercontent.com/4682328/27985852-d87a27cc-63c1-11e7-9eb3-efb33c9d3338.png)

**Comment by AlisonAMG** [comment]
All platforms completed. Task closed. :)

**Comment by Sandra97** [comment]
We should not close this issue. It should not be just a one shot, but shared regularly.

**Comment by Sandra97** [comment]
Merged to Glip tasks.
