### ISSUE TITLE
[DEV] Commits Milestone

### ISSUE THREAD

**Issue by wilsonge** [joomla/socialmedia#51]
### Description: 
I just realised we hit 30k commits in the CMS repo 

![image](https://user-images.githubusercontent.com/1986000/31181020-25ffc088-a918-11e7-9086-ded57f3ad162.png)

Might be worth a tweet

**Comment by Sandra97** [comment]
I'll prepare something.

**Comment by Sandra97** [comment]
Tweet done! 
Closing this issue.
