### ISSUE TITLE
Share RFP for Joomla shop

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/socialmedia#52]
### Description: 
We need to publish our RFP for a new Joomla shop.
https://www.opensourcematters.org/organisation/requests-for-proposals/260-request-for-proposal-joomla-merchandise-shop.html

### Date tweet should be done (at least 7 days upfront)
ASAP

### Twitter text (optional)
We are looking for individuals or companies interested in running our online shop. Read our request for proposal here. https://www.opensourcematters.org/organisation/requests-for-proposals/260-request-for-proposal-joomla-merchandise-shop.html

**Comment by Sandra97** [comment]
Done on Twitter and the Fanpage

**Comment by hvdmeer** [comment]
Shared on LinkedIn

**Comment by aDaneInSpain** [comment]
Thanks
