### ISSUE TITLE
[OSM] Inform community that Joomla Shop RFP has been updated/extended

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/socialmedia#53]
### Description: 
We had many repetitive questions for the shop RFP and have answered them in the RFP and extended the deadline. People considering submitting a proposal should be notified.

### Date tweet should be done (at least 7 days upfront)
ASAP. 

### Twitter text (optional)
Please note that we have added additional clarifications to our Merchandise Shop RFP and extended the deadline for asking questions and submitting proposals. You still have time. https://www.opensourcematters.org/organisation/requests-for-proposals/260-request-for-proposal-joomla-merchandise-shop.html

**Comment by hvdmeer** [comment]
Hi @aDaneInSpain, I spotted one typo "postopne" while scanning through the article.

**Comment by aDaneInSpain** [comment]
Fixed. Thanks!
