### ISSUE TITLE
[REQUEST] Volunteers Portal - 1,000 Joomlers

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#6]
We will soon reach 1,000 volunteers on the Portal (currently 980).

It could be the right time to say thank you, promote the Portal by asking people to register and to read the reports. 

If ok, could anyone create a pic with this milestone?

- [x] Facebook fan page
- [x] Google+
- [x] Twitter
- [x] Instagram
- [x] LinkedIn
- [x] Pinterest
- [x] Facebook group

**Comment by Sandra97** [comment]
Facebook
![vp-facebook](https://user-images.githubusercontent.com/4682328/27049801-ca81c9e4-4f86-11e7-83d9-987c88b7da4d.png)

Instagram
![vp-instagram](https://user-images.githubusercontent.com/4682328/27049803-cb5136ca-4f86-11e7-9d05-9486b73ce20f.png)

Twitter
![vp-twitter](https://user-images.githubusercontent.com/4682328/27049802-cac234ca-4f86-11e7-8281-5aaf8b5b1c48.png)

**Comment by AlisonAMG** [comment]
Beautiful job! Wow nice.

**Comment by AlisonAMG** [comment]
Did we meet 1000 yet? Watching this to post.

**Comment by Sandra97** [comment]
Nope. 984 currently as mentioned on the VP

**Comment by Sandra97** [comment]
992 now and new pics to replace the previous
![1000-joomlers-facebook](https://user-images.githubusercontent.com/4682328/27498763-f3822290-5836-11e7-858b-5055dd5503c5.png)
![Uploading 1000-joomlers-instagram.png…]()
![Uploading 1000-joomlers-twitter.png…]()

**Comment by Sandra97** [comment]
Ok, not enough connection to upload the other pics. Will try later

**Comment by Sandra97** [comment]
![1000-joomlers-twitter](https://user-images.githubusercontent.com/4682328/27498904-929239b0-5837-11e7-8331-aff67055a5e1.png)

**Comment by Sandra97** [comment]
![1000-joomlers-instagram](https://user-images.githubusercontent.com/4682328/27498926-b40e513c-5837-11e7-87ac-4ef4654f3f35.png)

**Comment by Sandra97** [comment]
We reached this morning 1,000 Joomlers. Let's wait to have over 1,002 to post all this.

**Comment by yvesh** [comment]
1001 :)

**Comment by Sandra97** [comment]
I know ;)

**Comment by AlisonAMG** [comment]
We're posting this Friday for Open Source day right?

**Comment by Sandra97** [comment]
Nope, note related. 
Open Source Friday is an initiative by GitHub: https://github.com/blog/2386-contribute-on-open-source-friday

**Comment by hvdmeer** [comment]
994 now, duplicate entries deleted. I should've checked for that earlier. ;)
BTW: I'm not on the Volunteer team, just found some duplicates when I was searching for myself.

**Comment by Sandra97** [comment]
@hvdmeer, I know your goal was just to screw up my planning! ;)

**Comment by hvdmeer** [comment]
Darn. Was it that obvious?

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sanderpotjer** [comment]
Graphics are great, thanks all!

**Comment by Sandra97** [comment]
Thanks Sander!

**Comment by Sandra97** [comment]
UPDATE! 1,004 Joomlers.
Please share the news as of tomorrow or Thurday.
Thank you!!!
And don't forget to ask people to register on the site https://volunteers.joomla.org/register

**Comment by Sandra97** [comment]
1,000+ #Joomlers have already registered to the #Voluntters Portal
Are you one of them?
If not, go to https://volunteers.joomla.org/register
#volunteer

**Comment by yvesh** [comment]
@Sandra97 Typo: Voluntters :-)

**Comment by Sandra97** [comment]
Thanks Yves!
