### ISSUE TITLE
[DEV] Developer Newsletter

### ISSUE THREAD

**Issue by Sandra97** [joomla/socialmedia#7]
Dev Newsletter is ready.

Please share the news and invite people to subscribe:
https://developer.joomla.org/newsletter.html

![joomla-newsletter](https://user-images.githubusercontent.com/4682328/27984243-a051783c-639e-11e7-83cf-d52d2a104ef2.jpg)

Instagram
![newsletterdev](https://user-images.githubusercontent.com/4682328/27984244-a0524474-639e-11e7-93a6-30061ff7affd.png)

**Comment by AlisonAMG** [comment]
I saw posts about this going around yesterday and liked and shared some but just went to the JDev Twitter and am not seeing the post.

**Comment by Sandra97** [comment]
I did a post for the jorg newsletter on my personal account, nothing yet for dev.
I will do the Tweet tomorrow on the dev acount, please do not share it now so that we don't do posts about 2 different newsletters at nearly the same time

**Comment by Sandra97** [comment]
We should not close this issue. It should not be just a one shot, but shared regularly.

**Comment by Sandra97** [comment]
Merged to Glip tasks.
