### ISSUE TITLE
[REQUEST] JoomlaDay Australia promotion

### ISSUE THREAD

**Issue by pbwebdev** [joomla/socialmedia#8]
### Description: 
Little bit of social media push and marketing for our upcoming event this weekend.
http://joomladay.org.au/

### Date tweet should be done (at least 7 days upfront)
Apologies but the event is this weekend and any sort of push when ever you can for the event would be appreciated.

### Twitter text (optional)
JoomlaDay Australia this weekend 17th-18th June 2 Day event. Tickets still available http://joomladay.org.au/ You can also become Joomla certified!

### Additional comments
Our ticket sales are the lowest they have every been, especially for Sydney. Meetup/JUG meetings are dwindling as well. Will be hard to keep things going for us.

**Comment by pbwebdev** [comment]
JoomlaDay Australia Twitter account - https://twitter.com/joomladayau
Facebook Page - https://www.facebook.com/JoomlaDayAu

**Comment by Radek-Suski** [comment]
@pbwebdev what would be the best time (UTC) to share it?

**Comment by AlisonAMG** [comment]
We should have graphics at the ready from the last time we shared the event also.

**Comment by AlisonAMG** [comment]
![jdoz](https://user-images.githubusercontent.com/3825882/27084285-46ecbf7e-5019-11e7-89e9-661732cc69d2.png)

The FB image for JD OZ

**Comment by AlisonAMG** [comment]
Don't miss out! #JoomlaDay Australia is June 17 - 18th in Sydney. Go NOW!
You can get your tickets at https://joomladay.org.au/ #Joomla #event

**Comment by SigsiuTrinity** [comment]
added the image to the repository

**Comment by SigsiuTrinity** [comment]
- [x] Facebook fan page
- [ ] Twitter
- [ ] Instagram
- [ ] LinkedIn
- [ ] Pinterest
- [ ] Facebook group

**Comment by AlisonAMG** [comment]
And G+

**Comment by SigsiuTrinity** [comment]
Google+ added :)

**Comment by Sandra97** [comment]
Already posted on Instagram on May 25th and it's the best practice to post twice the same pic on Instagram

**Comment by pbwebdev** [comment]
6:00 am UTC or 9pm UTC give or take an hour is suitable for an Australian audience.

Thank you team @AlisonAMG @Radek-Suski

**Comment by pbwebdev** [comment]
Really appreciate the social love! Lets hope it spikes and leads to a sale or two.

**Comment by AlisonAMG** [comment]
Wishing you all the very best at the event!

**Comment by AlisonAMG** [comment]
Promotion repeated across all but Instagram where not advisable to duplicate. Request completed. :)
