### ISSUE TITLE
[REQUEST] Call for members for Template Directory 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/socialmedia#9]
### Description: 
Please describe what and why you want something shared.
We need to share a a call for members to the Joomla! Template  Directory
https://volunteers.joomla.org/teams/template-directory-team#roles

### Additional comments

Done on:
- [x] Facebook Fan page
- [x] Google+
- [x] Twitter
- [x] Instagram
- [x] LinkedIn
- [x] Pinterest
- [x] Facebook Group

**Comment by AlisonAMG** [comment]
We are looking for members for the new #Joomla Template Directory. #JTD #teams 
https://volunteers.joomla.org/teams/template-directory-team#roles

Still room for 37 characters - suggestions?

**Comment by Sandra97** [comment]
We are looking for members for the new #Joomla #Template Directory.
 https://volunteers.joomla.org/teams/template-directory-team#roles
#JTD #teams #designer #Marketer #volunteer

**Comment by hvdmeer** [comment]
So? Can we start sending this message?

**Comment by AlisonAMG** [comment]
It needs images. I know what I want to make but got sidelined on other J images today.

**Comment by Sandra97** [comment]
@AlisonAMG could you create a pic so that we can share the post? Thank you!!!

**Comment by AlisonAMG** [comment]
Yup after I get the brochure for JDUK out the door.

**Comment by AlisonAMG** [comment]
Facebook
![jtd-fb](https://user-images.githubusercontent.com/3825882/27772339-0d7eab34-5f2e-11e7-8d2d-4553f5dd2455.jpg)
Instagram
![jtd-instagram](https://user-images.githubusercontent.com/3825882/27772338-0d7dd48e-5f2e-11e7-9191-d07f49a6b36b.jpg)
Twitter
![jtd-tw](https://user-images.githubusercontent.com/3825882/27772340-0d88c9a2-5f2e-11e7-8e6d-a4b5acb3e06f.jpg)

**Comment by Sandra97** [comment]
volunteers.joomla.org would be better ;)

**Comment by AlisonAMG** [comment]
Facebook
![jtd-fb](https://user-images.githubusercontent.com/3825882/27773970-b446da88-5f54-11e7-92b7-9e5a597441bf.jpg)
Instagram
![jtd-instagram](https://user-images.githubusercontent.com/3825882/27773971-b448ed14-5f54-11e7-9ec7-256cf3f3a09c.jpg)
Twitter
![jtd-tw](https://user-images.githubusercontent.com/3825882/27773972-b44964d8-5f54-11e7-9144-33f86e694911.jpg)

**Comment by AlisonAMG** [comment]
Facebook
![jtd-fb](https://user-images.githubusercontent.com/3825882/27773989-44557e22-5f55-11e7-8840-b5100d1f9919.jpg)
Instagram
![jtd-instagram](https://user-images.githubusercontent.com/3825882/27773990-4455d2f0-5f55-11e7-9a32-47bcca14be7f.jpg)
Twitter
![jtd-tw](https://user-images.githubusercontent.com/3825882/27773991-44585598-5f55-11e7-8052-085619757d54.jpg)

**Comment by Sandra97** [comment]
Better like that ;)

**Comment by Sandra97** [comment]
Task completed.
I'm closing this issue.
